# تنظیمات عمومی
general:
  language: "fa"
  theme: "light"
  log_level: "INFO"
  update_interval: "weekly"

# تنظیمات معاملات
trading:
  default_symbol: "XAUUSD_o"
  timeframe: "M5"
  risk_per_trade: 0.02  # 2% ریسک برای هر معامله
  max_positions: 5
  default_lot_size: 0.01
  
  # تنظیمات حد سود و ضرر
  sl_tp:
    use_fixed: true
    sl_pips: 50
    tp_pips: 100
    use_atr: false
    atr_period: 14
    sl_atr_multiplier: 2
    tp_atr_multiplier: 3

# تنظیمات نمودار
chart:
  default_timeframe: "M15"
  candle_count: 500
  indicators:
    - "RSI"
    - "MACD"
    - "MA"
    - "MFI"
# تنظیمات مدل‌ها
models:
  lstm:
    input_size: 5  # تعداد ویژگی‌ها
    hidden_size: 64
    num_layers: 2
    output_size: 1
    sequence_length: 50
    learning_rate: 0.001
    epochs: 20
    batch_size: 32    